### PR TITLE
proposal: Instance theme in the list for ease of community discovery

### PR DESCRIPTION
**Pull request by Hallicopter**
Similar to how instances in the fediverse are usually themed, I figured it would be easier for a new user to discover like-minded communities if we list the server theme.

### CODE REVIEW

**Comment by mouse-reeve** [comment]
Sounds good to me! Looks like you have a spelling error with `Deutsch`, but otherwise @tofuwabohu do you have a preference in how wyrms.de is characterized?

**Comment by Hallicopter** [comment]
> Looks like you have a spelling error with Deutsch

Whoops, my bad. Will make changes once @tofuwabohu is cool with the category I put in. It was just a placeholder since I am not aware of their instance theme.

**Comment by tofuwabohu** [comment]
Hi, I like the idea and while I don't have a perfect characterization for my instance in my mind currently, I don't want to hinder the process, so just go for it and I'll change it if I feel it's necessary. :)

Maybe, long term, the languages could be their own trait? While I and others active users post mostly German, most wyrms.de users are not German, so Englisch/Deutsch would be an bit correcter, I'm fine with either though.

**Comment by Hallicopter** [comment]
I have made the little spelling change. Also, how does the build for the website work? Does it build automatically when pushed to master, or up publish it manually later? Just curious.

**Comment by mouse-reeve** [comment]
Right now I'm build and push manually, but I'd like to get it happening automatically in a github action

**Pull request merged**
